export const SWIPE_THRESHOLD_RATIO = 0.38;
export const MIN_SWIPE_THRESHOLD = 100;
export const MAX_DRAG = 360;

export const DeveloperProfilesDemoData = [
  {
    id: "devansh-mishra",
    name: "Devansh Mishra",
    age: 27,
    verified: true,
    role: "Senior Backend Engineer",
    location: "Bengaluru, India",
    company: "Razorpay",
    experience: "6+ years",
    education: "B.Tech in Computer Science",
    bio: "Backend engineer who enjoys designing reliable systems, improving APIs, and solving problems that scale.",
    images: [
      "https://images.pexels.com/photos/9212726/pexels-photo-9212726.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/5483070/pexels-photo-5483070.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/5474282/pexels-photo-5474282.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/7988089/pexels-photo-7988089.jpeg?auto=compress&cs=tinysrgb&w=900",
    ],
    isOnline: true,
    lastSeen: "Active now",
    responseTime: "Usually replies within an hour",
    availability: "Open to opportunities",
    techStack: ["Node.js", "TypeScript", "PostgreSQL", "Redis", "Docker"],
    interests: ["System Design", "Open Source", "Cricket", "Coffee"],
    lookingFor: ["Developers", "Startup ideas", "Tech networking"],
    projects: 8,
    githubActivity: "Active",
  },

  {
    id: "ishaan-agarwal",
    name: "Ishaan Agarwal",
    age: 25,
    verified: true,
    role: "Frontend Engineer",
    location: "Mumbai, India",
    company: "Zepto",
    experience: "4+ years",
    education: "B.E. in Computer Engineering",
    bio: "Frontend engineer obsessed with smooth interactions, clean interfaces, and turning complex ideas into simple products.",
    images: [
      "https://images.pexels.com/photos/3400560/pexels-photo-3400560.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/3400574/pexels-photo-3400574.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/3862142/pexels-photo-3862142.jpeg?auto=compress&cs=tinysrgb&w=900",
    ],
    isOnline: false,
    lastSeen: "Active 2h ago",
    responseTime: "Usually replies within a few hours",
    availability: "Open to networking",
    techStack: [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Framer Motion",
    ],
    interests: ["UI Engineering", "Design Systems", "Photography", "Gaming"],
    lookingFor: ["Frontend developers", "Designers", "Side projects"],
    projects: 12,
    githubActivity: "Very active",
  },

  {
    id: "rohit-bansal",
    name: "Rohit Bansal",
    age: 29,
    verified: true,
    role: "Full Stack Engineer",
    location: "Pune, India",
    company: "Persistent Systems",
    experience: "7+ years",
    education: "M.Tech in Computer Science",
    bio: "Full stack engineer building practical products from idea to production. Big fan of clean architecture and good documentation.",
    images: [
      "https://images.pexels.com/photos/37556617/pexels-photo-37556617.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/31851560/pexels-photo-31851560.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/16129728/pexels-photo-16129728.jpeg?auto=compress&cs=tinysrgb&w=900",
    ],
    isOnline: true,
    lastSeen: "Active now",
    responseTime: "Usually replies within 30 min",
    availability: "Available for collaboration",
    techStack: ["React", "Node.js", "MongoDB", "AWS", "GraphQL"],
    interests: ["Startups", "Cloud Architecture", "Travel", "Badminton"],
    lookingFor: ["Founders", "Developers", "Startup projects"],
    projects: 15,
    githubActivity: "Active",
  },

  {
    id: "samar-khan",
    name: "Samar Khan",
    age: 28,
    verified: true,
    role: "Software Engineer",
    location: "Delhi, India",
    company: "Microsoft",
    experience: "6+ years",
    education: "B.Tech in Information Technology",
    bio: "Software engineer focused on Python, distributed systems, and building products that are fast, maintainable, and boring in production.",
    images: [
      "https://images.pexels.com/photos/12596735/pexels-photo-12596735.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/13439444/pexels-photo-13439444.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/31207769/pexels-photo-31207769.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/33261955/pexels-photo-33261955.jpeg?auto=compress&cs=tinysrgb&w=900",
    ],
    isOnline: true,
    lastSeen: "Active now",
    responseTime: "Usually replies within an hour",
    availability: "Open to opportunities",
    techStack: ["Python", "Django", "React", "PostgreSQL", "Celery"],
    interests: ["Machine Learning", "Reading", "Football", "Productivity"],
    lookingFor: ["Engineers", "AI enthusiasts", "Tech communities"],
    projects: 10,
    githubActivity: "Active",
  },

  {
    id: "kabir-jain",
    name: "Kabir Jain",
    age: 26,
    verified: false,
    role: "DevOps Engineer",
    location: "Hyderabad, India",
    company: "Deloitte",
    experience: "5+ years",
    education: "B.Tech in Computer Science",
    bio: "DevOps engineer who likes automating repetitive work, improving deployments, and keeping production calm.",
    images: [
      "https://images.pexels.com/photos/8128186/pexels-photo-8128186.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/5483057/pexels-photo-5483057.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/7988089/pexels-photo-7988089.jpeg?auto=compress&cs=tinysrgb&w=900",
    ],
    isOnline: false,
    lastSeen: "Active yesterday",
    responseTime: "Usually replies within a few hours",
    availability: "Open to networking",
    techStack: ["AWS", "Kubernetes", "Terraform", "Docker", "Jenkins"],
    interests: ["Cloud Infrastructure", "Automation", "Cycling", "Photography"],
    lookingFor: ["Cloud engineers", "DevOps communities", "Open source"],
    projects: 9,
    githubActivity: "Active",
  },

  {
    id: "aaryan-kapoor",
    name: "Aaryan Kapoor",
    age: 24,
    verified: true,
    role: "React Native Developer",
    location: "Noida, India",
    company: "Paytm",
    experience: "3+ years",
    education: "BCA",
    bio: "Mobile developer building polished cross-platform experiences. I enjoy turning product ideas into apps people actually want to use.",
    images: [
      "https://images.pexels.com/photos/6937693/pexels-photo-6937693.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/4307853/pexels-photo-4307853.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/4078343/pexels-photo-4078343.jpeg?auto=compress&cs=tinysrgb&w=900",
    ],
    isOnline: true,
    lastSeen: "Active now",
    responseTime: "Usually replies within 20 min",
    availability: "Available for collaboration",
    techStack: ["React Native", "TypeScript", "Expo", "Firebase", "Redux"],
    interests: ["Mobile Development", "Startups", "Music", "Badminton"],
    lookingFor: ["Mobile developers", "Product builders", "Startup ideas"],
    projects: 7,
    githubActivity: "Very active",
  },

  {
    id: "harsh-vardhan",
    name: "Harsh Vardhan",
    age: 30,
    verified: true,
    role: "Cloud Architect",
    location: "Chennai, India",
    company: "Freshworks",
    experience: "9+ years",
    education: "M.Tech in Cloud Computing",
    bio: "Cloud architect focused on scalable infrastructure, platform engineering, and simplifying complex distributed systems.",
    images: [
      "https://images.pexels.com/photos/37826990/pexels-photo-37826990.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/35977198/pexels-photo-35977198.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/7580992/pexels-photo-7580992.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/8729954/pexels-photo-8729954.jpeg?auto=compress&cs=tinysrgb&w=900",
    ],
    isOnline: false,
    lastSeen: "Active 5h ago",
    responseTime: "Usually replies within a few hours",
    availability: "Open to mentoring",
    techStack: ["AWS", "Azure", "Terraform", "Kubernetes", "Linux"],
    interests: ["Cloud Architecture", "System Design", "Running", "Travel"],
    lookingFor: ["Senior engineers", "Cloud professionals", "Mentorship"],
    projects: 18,
    githubActivity: "Active",
  },

  {
    id: "nikhil-sen",
    name: "Nikhil Sen",
    age: 27,
    verified: true,
    role: "Software Developer",
    location: "Kolkata, India",
    company: "TCS",
    experience: "5+ years",
    education: "B.Tech in Computer Science",
    bio: "Java developer working on backend systems and event-driven applications. Always interested in learning something new.",
    images: [
      "https://images.pexels.com/photos/33261967/pexels-photo-33261967.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/33261951/pexels-photo-33261951.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/31747187/pexels-photo-31747187.jpeg?auto=compress&cs=tinysrgb&w=900",
    ],
    isOnline: true,
    lastSeen: "Active now",
    responseTime: "Usually replies within an hour",
    availability: "Open to opportunities",
    techStack: ["Java", "Spring Boot", "MySQL", "Kafka", "Docker"],
    interests: [
      "Backend Development",
      "Distributed Systems",
      "Chess",
      "Movies",
    ],
    lookingFor: ["Backend engineers", "Tech discussions", "Side projects"],
    projects: 11,
    githubActivity: "Active",
  },

  {
    id: "yash-malhotra",
    name: "Yash Malhotra",
    age: 25,
    verified: false,
    role: "Frontend Developer",
    location: "Gurugram, India",
    company: "MakeMyTrip",
    experience: "4+ years",
    education: "B.Tech in Information Technology",
    bio: "Frontend developer who cares about accessibility, performance, and making interfaces feel effortless.",
    images: [
      "https://images.pexels.com/photos/29898849/pexels-photo-29898849.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/1067622/pexels-photo-1067622.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/6804604/pexels-photo-6804604.jpeg?auto=compress&cs=tinysrgb&w=900",
    ],
    isOnline: true,
    lastSeen: "Active now",
    responseTime: "Usually replies within 30 min",
    availability: "Available for collaboration",
    techStack: ["JavaScript", "React", "Next.js", "Tailwind CSS", "Jest"],
    interests: ["Web Performance", "UI/UX", "Travel", "Photography"],
    lookingFor: ["Frontend developers", "Designers", "Creative projects"],
    projects: 13,
    githubActivity: "Very active",
  },

  {
    id: "vihaan-reddy",
    name: "Vihaan Reddy",
    age: 29,
    verified: true,
    role: "Senior Software Engineer",
    location: "Hyderabad, India",
    company: "ServiceNow",
    experience: "7+ years",
    education: "B.Tech in Computer Science",
    bio: "Senior software engineer with a full-stack background and a strong interest in scalable products and developer experience.",
    images: [
      "https://images.pexels.com/photos/4307818/pexels-photo-4307818.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/4307821/pexels-photo-4307821.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/4307852/pexels-photo-4307852.jpeg?auto=compress&cs=tinysrgb&w=900",
      "https://images.pexels.com/photos/4307857/pexels-photo-4307857.jpeg?auto=compress&cs=tinysrgb&w=900",
    ],
    isOnline: false,
    lastSeen: "Active 3h ago",
    responseTime: "Usually replies within an hour",
    availability: "Open to opportunities",
    techStack: ["TypeScript", "React", "Node.js", "PostgreSQL", "AWS"],
    interests: ["Developer Tools", "System Design", "Football", "Travel"],
    lookingFor: ["Senior developers", "Builders", "Tech networking"],
    projects: 16,
    githubActivity: "Active",
  },
];

export type DeveloperProfile = (typeof DeveloperProfilesDemoData)[number];
